# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerAgentTail < Formula
  desc "Auto-discover Docker containers, tail their logs, and write structured files for AI agents"
  homepage "https://docker-agent-tail.michaelscotello.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mscotello/docker-agent-tail/releases/download/v0.1.3/docker-agent-tail_0.1.3_darwin_amd64.tar.gz"
      sha256 "c9c7368423a1c74d9f91b216aaa9a3391b44fe98180ebaad60117b96429ded7b"

      define_method(:install) do
        bin.install "docker-agent-tail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mscotello/docker-agent-tail/releases/download/v0.1.3/docker-agent-tail_0.1.3_darwin_arm64.tar.gz"
      sha256 "d115f9e4698c152b187f1af8e204c14bf544c6f614b8171bbad386112f65fd80"

      define_method(:install) do
        bin.install "docker-agent-tail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mscotello/docker-agent-tail/releases/download/v0.1.3/docker-agent-tail_0.1.3_linux_amd64.tar.gz"
      sha256 "5a6047c2ffe725dc5aedbd3e816c35b0b09755f5c3aab3e7adbe08e634b3554a"
      define_method(:install) do
        bin.install "docker-agent-tail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mscotello/docker-agent-tail/releases/download/v0.1.3/docker-agent-tail_0.1.3_linux_arm64.tar.gz"
      sha256 "6f7fee95ec6dbbda8249e1d121a986ca44427301a0bc64a3064c75f35fd51ada"
      define_method(:install) do
        bin.install "docker-agent-tail"
      end
    end
  end

  test do
    system "#{bin}/docker-agent-tail", "--help"
  end
end
